### ISSUE TITLE
[Feature Request] Flatpak release

### ISSUE THREAD

**Issue by deadmeu** [Mr-Wiseguy/Zelda64Recomp#44]
Opening this ticket for the purposes of tracking Flatpak support, as mentioned in https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/21#issuecomment-2105386686.

I would really appreciate a Flatpak release be made available via Flathub.

**Comment by A6GibKm** [comment]
Btw, you can place the decompressed build + rom at ~/Games, then launch bottles (or any other flatpak with the right dependencies, prob steam(?)) via 
```
flatpak run --command=sh com.usebottles.bottles
```
then `cd` into the dir and execute it from the sandboxed shell.

**Comment by ColinKinloch** [comment]
It looks like the ROM is required at compile time so a flathub release would unfortunately probably just be redistributing the pre-compiled binary. (I guess it saves compiling a mips toolchain)

I'm not interested in being the package maintainer it but this seems to work:
```yaml
app-id: org.n64recomp.Zelda64Recomp
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: Zelda64Recompiled-wrapper

finish-args:
  - --socket=x11
  - --share=ipc
  - --socket=pulseaudio
  - --device=all
  - --filesystem=home:ro

modules:
  - name: Zelda64Recomp
    buildsystem: simple
    build-commands:
      - mkdir -p ${FLATPAK_DEST}/bin
      - cp -r ./* ${FLATPAK_DEST}/bin
    sources:
      - type: archive
        url: https://github.com/Zelda64Recomp/Zelda64Recomp/releases/download/v1.0.1/Zelda64Recompiled-v1.0.1-Linux.tar.gz
        sha256: dff230e4ca0c8c7b84e00a36574d25d8b25500a956dabe997fdecca352debc31
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/Zelda64Recomp/Zelda64Recomp/releases/latest
          version-query: .tag_name
          url-query: '[.assets[] | select(.name | test("Zelda64Recompiled-v[0-9.]+-Linux\\.tar\\.gz"))]
            | first | .browser_download_url'
      - type: script
        dest-filename: Zelda64Recompiled-wrapper
        commands:
          - cd /app/bin && ./Zelda64Recompiled
```

The filesystem permission could be removed if the NFD dialogue supported portals or if it were replaced with `GtkFileChooserNative`
